CREATE DATABASE IF NOT EXISTS core_opdata;
CREATE DATABASE IF NOT EXISTS core_server;
CREATE DATABASE IF NOT EXISTS core_translog;


DROP USER IF EXISTS pos@localhost;

CREATE USER pos@localhost
IDENTIFIED BY PASSWORD '*697FFC9F3E8357F823548EE466D17FDC1B5A66DD';

GRANT
	SELECT, INSERT, UPDATE, DELETE,
	CREATE, DROP, INDEX, ALTER,
	CREATE TEMPORARY TABLES, CREATE VIEW, EVENT, TRIGGER,
	SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE
ON core_opdata.*
TO pos@localhost;

GRANT
	SELECT, INSERT, UPDATE, DELETE,
	CREATE, DROP, INDEX, ALTER,
	CREATE TEMPORARY TABLES, CREATE VIEW, EVENT, TRIGGER,
	SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE
ON core_server.*
TO pos@localhost;

GRANT
	SELECT, INSERT, UPDATE, DELETE,
	CREATE, DROP, INDEX, ALTER,
	CREATE TEMPORARY TABLES, CREATE VIEW, EVENT, TRIGGER,
	SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE
ON core_translog.*
TO pos@localhost;


DROP USER IF EXISTS fannie@'192.168.1.%';

CREATE USER fannie@'192.168.1.%'
IDENTIFIED BY PASSWORD '*C06C1B8C66BB23C8EA3CB31321B656F0CE43ECE8';

GRANT ALL PRIVILEGES
ON core_opdata.*
TO fannie@'192.168.1.%';

GRANT ALL PRIVILEGES
ON core_server.*
TO fannie@'192.168.1.%';

GRANT ALL PRIVILEGES
ON core_translog.*
TO fannie@'192.168.1.%';


USE core_translog;


TRUNCATE TABLE taxrates;

INSERT taxrates ( id, rate, description )
VALUES ( 1, 0.035, 'UEZ' );
