DROP USER pos@localhost;

CREATE USER pos@localhost
IDENTIFIED BY PASSWORD '*697FFC9F3E8357F823548EE466D17FDC1B5A66DD';

GRANT
	SELECT, INSERT, UPDATE, DELETE,
	CREATE, DROP, INDEX, ALTER,
	CREATE TEMPORARY TABLES, CREATE VIEW, EVENT, TRIGGER,
	SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE
ON core_opdata.*
TO pos@localhost;

GRANT
	SELECT, INSERT, UPDATE, DELETE,
	CREATE, DROP, INDEX, ALTER,
	CREATE TEMPORARY TABLES, CREATE VIEW, EVENT, TRIGGER,
	SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE
ON core_server.*
TO pos@localhost;

GRANT
	SELECT, INSERT, UPDATE, DELETE,
	CREATE, DROP, INDEX, ALTER,
	CREATE TEMPORARY TABLES, CREATE VIEW, EVENT, TRIGGER,
	SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE
ON core_translog.*
TO pos@localhost;


USE core_translog;


TRUNCATE TABLE taxrates;

INSERT taxrates ( id, rate, description )
VALUES ( 1, 0.035, 'UEZ' );
